//
//  CountryCodes.swift
//  MobilyflowSDK
//
//  Created by Gregoire Taja on 04/09/2025.
//

struct CountryCode {
    let name: String
    let alpha2: String
    let alpha3: String
}

class CountryCodes {
    private static let _countries: [CountryCode] = [
        CountryCode(name: "Afghanistan", alpha2: "AF", alpha3: "AFG"),
        CountryCode(name: "Åland Islands", alpha2: "AX", alpha3: "ALA"),
        CountryCode(name: "Albania", alpha2: "AL", alpha3: "ALB"),
        CountryCode(name: "Algeria", alpha2: "DZ", alpha3: "DZA"),
        CountryCode(name: "American Samoa", alpha2: "AS", alpha3: "ASM"),
        CountryCode(name: "Andorra", alpha2: "AD", alpha3: "AND"),
        CountryCode(name: "Angola", alpha2: "AO", alpha3: "AGO"),
        CountryCode(name: "Anguilla", alpha2: "AI", alpha3: "AIA"),
        CountryCode(name: "Antarctica", alpha2: "AQ", alpha3: "ATA"),
        CountryCode(name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG"),
        CountryCode(name: "Argentina", alpha2: "AR", alpha3: "ARG"),
        CountryCode(name: "Armenia", alpha2: "AM", alpha3: "ARM"),
        CountryCode(name: "Aruba", alpha2: "AW", alpha3: "ABW"),
        CountryCode(name: "Australia", alpha2: "AU", alpha3: "AUS"),
        CountryCode(name: "Austria", alpha2: "AT", alpha3: "AUT"),
        CountryCode(name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE"),
        CountryCode(name: "Bahamas", alpha2: "BS", alpha3: "BHS"),
        CountryCode(name: "Bahrain", alpha2: "BH", alpha3: "BHR"),
        CountryCode(name: "Bangladesh", alpha2: "BD", alpha3: "BGD"),
        CountryCode(name: "Barbados", alpha2: "BB", alpha3: "BRB"),
        CountryCode(name: "Belarus", alpha2: "BY", alpha3: "BLR"),
        CountryCode(name: "Belgium", alpha2: "BE", alpha3: "BEL"),
        CountryCode(name: "Belize", alpha2: "BZ", alpha3: "BLZ"),
        CountryCode(name: "Benin", alpha2: "BJ", alpha3: "BEN"),
        CountryCode(name: "Bermuda", alpha2: "BM", alpha3: "BMU"),
        CountryCode(name: "Bhutan", alpha2: "BT", alpha3: "BTN"),
        CountryCode(name: "Bolivia, Plurinational State of", alpha2: "BO", alpha3: "BOL"),
        CountryCode(name: "Bonaire, Sint Eustatius and Saba", alpha2: "BQ", alpha3: "BES"),
        CountryCode(name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH"),
        CountryCode(name: "Botswana", alpha2: "BW", alpha3: "BWA"),
        CountryCode(name: "Bouvet Island", alpha2: "BV", alpha3: "BVT"),
        CountryCode(name: "Brazil", alpha2: "BR", alpha3: "BRA"),
        CountryCode(name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT"),
        CountryCode(name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN"),
        CountryCode(name: "Bulgaria", alpha2: "BG", alpha3: "BGR"),
        CountryCode(name: "Burkina Faso", alpha2: "BF", alpha3: "BFA"),
        CountryCode(name: "Burundi", alpha2: "BI", alpha3: "BDI"),
        CountryCode(name: "Cabo Verde", alpha2: "CV", alpha3: "CPV"),
        CountryCode(name: "Cambodia", alpha2: "KH", alpha3: "KHM"),
        CountryCode(name: "Cameroon", alpha2: "CM", alpha3: "CMR"),
        CountryCode(name: "Canada", alpha2: "CA", alpha3: "CAN"),
        CountryCode(name: "Cayman Islands", alpha2: "KY", alpha3: "CYM"),
        CountryCode(name: "Central African Republic", alpha2: "CF", alpha3: "CAF"),
        CountryCode(name: "Chad", alpha2: "TD", alpha3: "TCD"),
        CountryCode(name: "Chile", alpha2: "CL", alpha3: "CHL"),
        CountryCode(name: "China", alpha2: "CN", alpha3: "CHN"),
        CountryCode(name: "Christmas Island", alpha2: "CX", alpha3: "CXR"),
        CountryCode(name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK"),
        CountryCode(name: "Colombia", alpha2: "CO", alpha3: "COL"),
        CountryCode(name: "Comoros", alpha2: "KM", alpha3: "COM"),
        CountryCode(name: "Congo", alpha2: "CG", alpha3: "COG"),
        CountryCode(name: "Congo, Democratic Republic of the", alpha2: "CD", alpha3: "COD"),
        CountryCode(name: "Cook Islands", alpha2: "CK", alpha3: "COK"),
        CountryCode(name: "Costa Rica", alpha2: "CR", alpha3: "CRI"),
        CountryCode(name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV"),
        CountryCode(name: "Croatia", alpha2: "HR", alpha3: "HRV"),
        CountryCode(name: "Cuba", alpha2: "CU", alpha3: "CUB"),
        CountryCode(name: "Curaçao", alpha2: "CW", alpha3: "CUW"),
        CountryCode(name: "Cyprus", alpha2: "CY", alpha3: "CYP"),
        CountryCode(name: "Czechia", alpha2: "CZ", alpha3: "CZE"),
        CountryCode(name: "Denmark", alpha2: "DK", alpha3: "DNK"),
        CountryCode(name: "Djibouti", alpha2: "DJ", alpha3: "DJI"),
        CountryCode(name: "Dominica", alpha2: "DM", alpha3: "DMA"),
        CountryCode(name: "Dominican Republic", alpha2: "DO", alpha3: "DOM"),
        CountryCode(name: "Ecuador", alpha2: "EC", alpha3: "ECU"),
        CountryCode(name: "Egypt", alpha2: "EG", alpha3: "EGY"),
        CountryCode(name: "El Salvador", alpha2: "SV", alpha3: "SLV"),
        CountryCode(name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ"),
        CountryCode(name: "Eritrea", alpha2: "ER", alpha3: "ERI"),
        CountryCode(name: "Estonia", alpha2: "EE", alpha3: "EST"),
        CountryCode(name: "Eswatini", alpha2: "SZ", alpha3: "SWZ"),
        CountryCode(name: "Ethiopia", alpha2: "ET", alpha3: "ETH"),
        CountryCode(name: "Falkland Islands (Malvinas)", alpha2: "FK", alpha3: "FLK"),
        CountryCode(name: "Faroe Islands", alpha2: "FO", alpha3: "FRO"),
        CountryCode(name: "Fiji", alpha2: "FJ", alpha3: "FJI"),
        CountryCode(name: "Finland", alpha2: "FI", alpha3: "FIN"),
        CountryCode(name: "France", alpha2: "FR", alpha3: "FRA"),
        CountryCode(name: "French Guiana", alpha2: "GF", alpha3: "GUF"),
        CountryCode(name: "French Polynesia", alpha2: "PF", alpha3: "PYF"),
        CountryCode(name: "French Southern Territories", alpha2: "TF", alpha3: "ATF"),
        CountryCode(name: "Gabon", alpha2: "GA", alpha3: "GAB"),
        CountryCode(name: "Gambia", alpha2: "GM", alpha3: "GMB"),
        CountryCode(name: "Georgia", alpha2: "GE", alpha3: "GEO"),
        CountryCode(name: "Germany", alpha2: "DE", alpha3: "DEU"),
        CountryCode(name: "Ghana", alpha2: "GH", alpha3: "GHA"),
        CountryCode(name: "Gibraltar", alpha2: "GI", alpha3: "GIB"),
        CountryCode(name: "Greece", alpha2: "GR", alpha3: "GRC"),
        CountryCode(name: "Greenland", alpha2: "GL", alpha3: "GRL"),
        CountryCode(name: "Grenada", alpha2: "GD", alpha3: "GRD"),
        CountryCode(name: "Guadeloupe", alpha2: "GP", alpha3: "GLP"),
        CountryCode(name: "Guam", alpha2: "GU", alpha3: "GUM"),
        CountryCode(name: "Guatemala", alpha2: "GT", alpha3: "GTM"),
        CountryCode(name: "Guernsey", alpha2: "GG", alpha3: "GGY"),
        CountryCode(name: "Guinea", alpha2: "GN", alpha3: "GIN"),
        CountryCode(name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB"),
        CountryCode(name: "Guyana", alpha2: "GY", alpha3: "GUY"),
        CountryCode(name: "Haiti", alpha2: "HT", alpha3: "HTI"),
        CountryCode(name: "Heard Island and McDonald Islands", alpha2: "HM", alpha3: "HMD"),
        CountryCode(name: "Holy See", alpha2: "VA", alpha3: "VAT"),
        CountryCode(name: "Honduras", alpha2: "HN", alpha3: "HND"),
        CountryCode(name: "Hong Kong", alpha2: "HK", alpha3: "HKG"),
        CountryCode(name: "Hungary", alpha2: "HU", alpha3: "HUN"),
        CountryCode(name: "Iceland", alpha2: "IS", alpha3: "ISL"),
        CountryCode(name: "India", alpha2: "IN", alpha3: "IND"),
        CountryCode(name: "Indonesia", alpha2: "ID", alpha3: "IDN"),
        CountryCode(name: "Iran, Islamic Republic of", alpha2: "IR", alpha3: "IRN"),
        CountryCode(name: "Iraq", alpha2: "IQ", alpha3: "IRQ"),
        CountryCode(name: "Ireland", alpha2: "IE", alpha3: "IRL"),
        CountryCode(name: "Isle of Man", alpha2: "IM", alpha3: "IMN"),
        CountryCode(name: "Israel", alpha2: "IL", alpha3: "ISR"),
        CountryCode(name: "Italy", alpha2: "IT", alpha3: "ITA"),
        CountryCode(name: "Jamaica", alpha2: "JM", alpha3: "JAM"),
        CountryCode(name: "Japan", alpha2: "JP", alpha3: "JPN"),
        CountryCode(name: "Jersey", alpha2: "JE", alpha3: "JEY"),
        CountryCode(name: "Jordan", alpha2: "JO", alpha3: "JOR"),
        CountryCode(name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ"),
        CountryCode(name: "Kenya", alpha2: "KE", alpha3: "KEN"),
        CountryCode(name: "Kiribati", alpha2: "KI", alpha3: "KIR"),
        CountryCode(name: "Korea, Democratic People's Republic of", alpha2: "KP", alpha3: "PRK"),
        CountryCode(name: "Korea, Republic of", alpha2: "KR", alpha3: "KOR"),
        CountryCode(name: "Kuwait", alpha2: "KW", alpha3: "KWT"),
        CountryCode(name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ"),
        CountryCode(name: "Lao People's Democratic Republic", alpha2: "LA", alpha3: "LAO"),
        CountryCode(name: "Latvia", alpha2: "LV", alpha3: "LVA"),
        CountryCode(name: "Lebanon", alpha2: "LB", alpha3: "LBN"),
        CountryCode(name: "Lesotho", alpha2: "LS", alpha3: "LSO"),
        CountryCode(name: "Liberia", alpha2: "LR", alpha3: "LBR"),
        CountryCode(name: "Libya", alpha2: "LY", alpha3: "LBY"),
        CountryCode(name: "Liechtenstein", alpha2: "LI", alpha3: "LIE"),
        CountryCode(name: "Lithuania", alpha2: "LT", alpha3: "LTU"),
        CountryCode(name: "Luxembourg", alpha2: "LU", alpha3: "LUX"),
        CountryCode(name: "Macao", alpha2: "MO", alpha3: "MAC"),
        CountryCode(name: "Madagascar", alpha2: "MG", alpha3: "MDG"),
        CountryCode(name: "Malawi", alpha2: "MW", alpha3: "MWI"),
        CountryCode(name: "Malaysia", alpha2: "MY", alpha3: "MYS"),
        CountryCode(name: "Maldives", alpha2: "MV", alpha3: "MDV"),
        CountryCode(name: "Mali", alpha2: "ML", alpha3: "MLI"),
        CountryCode(name: "Malta", alpha2: "MT", alpha3: "MLT"),
        CountryCode(name: "Marshall Islands", alpha2: "MH", alpha3: "MHL"),
        CountryCode(name: "Martinique", alpha2: "MQ", alpha3: "MTQ"),
        CountryCode(name: "Mauritania", alpha2: "MR", alpha3: "MRT"),
        CountryCode(name: "Mauritius", alpha2: "MU", alpha3: "MUS"),
        CountryCode(name: "Mayotte", alpha2: "YT", alpha3: "MYT"),
        CountryCode(name: "Mexico", alpha2: "MX", alpha3: "MEX"),
        CountryCode(name: "Micronesia, Federated States of", alpha2: "FM", alpha3: "FSM"),
        CountryCode(name: "Moldova, Republic of", alpha2: "MD", alpha3: "MDA"),
        CountryCode(name: "Monaco", alpha2: "MC", alpha3: "MCO"),
        CountryCode(name: "Mongolia", alpha2: "MN", alpha3: "MNG"),
        CountryCode(name: "Montenegro", alpha2: "ME", alpha3: "MNE"),
        CountryCode(name: "Montserrat", alpha2: "MS", alpha3: "MSR"),
        CountryCode(name: "Morocco", alpha2: "MA", alpha3: "MAR"),
        CountryCode(name: "Mozambique", alpha2: "MZ", alpha3: "MOZ"),
        CountryCode(name: "Myanmar", alpha2: "MM", alpha3: "MMR"),
        CountryCode(name: "Namibia", alpha2: "NA", alpha3: "NAM"),
        CountryCode(name: "Nauru", alpha2: "NR", alpha3: "NRU"),
        CountryCode(name: "Nepal", alpha2: "NP", alpha3: "NPL"),
        CountryCode(name: "Netherlands, Kingdom of the", alpha2: "NL", alpha3: "NLD"),
        CountryCode(name: "New Caledonia", alpha2: "NC", alpha3: "NCL"),
        CountryCode(name: "New Zealand", alpha2: "NZ", alpha3: "NZL"),
        CountryCode(name: "Nicaragua", alpha2: "NI", alpha3: "NIC"),
        CountryCode(name: "Niger", alpha2: "NE", alpha3: "NER"),
        CountryCode(name: "Nigeria", alpha2: "NG", alpha3: "NGA"),
        CountryCode(name: "Niue", alpha2: "NU", alpha3: "NIU"),
        CountryCode(name: "Norfolk Island", alpha2: "NF", alpha3: "NFK"),
        CountryCode(name: "North Macedonia", alpha2: "MK", alpha3: "MKD"),
        CountryCode(name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP"),
        CountryCode(name: "Norway", alpha2: "NO", alpha3: "NOR"),
        CountryCode(name: "Oman", alpha2: "OM", alpha3: "OMN"),
        CountryCode(name: "Pakistan", alpha2: "PK", alpha3: "PAK"),
        CountryCode(name: "Palau", alpha2: "PW", alpha3: "PLW"),
        CountryCode(name: "Palestine, State of", alpha2: "PS", alpha3: "PSE"),
        CountryCode(name: "Panama", alpha2: "PA", alpha3: "PAN"),
        CountryCode(name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG"),
        CountryCode(name: "Paraguay", alpha2: "PY", alpha3: "PRY"),
        CountryCode(name: "Peru", alpha2: "PE", alpha3: "PER"),
        CountryCode(name: "Philippines", alpha2: "PH", alpha3: "PHL"),
        CountryCode(name: "Pitcairn", alpha2: "PN", alpha3: "PCN"),
        CountryCode(name: "Poland", alpha2: "PL", alpha3: "POL"),
        CountryCode(name: "Portugal", alpha2: "PT", alpha3: "PRT"),
        CountryCode(name: "Puerto Rico", alpha2: "PR", alpha3: "PRI"),
        CountryCode(name: "Qatar", alpha2: "QA", alpha3: "QAT"),
        CountryCode(name: "Réunion", alpha2: "RE", alpha3: "REU"),
        CountryCode(name: "Romania", alpha2: "RO", alpha3: "ROU"),
        CountryCode(name: "Russian Federation", alpha2: "RU", alpha3: "RUS"),
        CountryCode(name: "Rwanda", alpha2: "RW", alpha3: "RWA"),
        CountryCode(name: "Saint Barthélemy", alpha2: "BL", alpha3: "BLM"),
        CountryCode(name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "SH", alpha3: "SHN"),
        CountryCode(name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA"),
        CountryCode(name: "Saint Lucia", alpha2: "LC", alpha3: "LCA"),
        CountryCode(name: "Saint Martin (French part)", alpha2: "MF", alpha3: "MAF"),
        CountryCode(name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM"),
        CountryCode(name: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT"),
        CountryCode(name: "Samoa", alpha2: "WS", alpha3: "WSM"),
        CountryCode(name: "San Marino", alpha2: "SM", alpha3: "SMR"),
        CountryCode(name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP"),
        CountryCode(name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU"),
        CountryCode(name: "Senegal", alpha2: "SN", alpha3: "SEN"),
        CountryCode(name: "Serbia", alpha2: "RS", alpha3: "SRB"),
        CountryCode(name: "Seychelles", alpha2: "SC", alpha3: "SYC"),
        CountryCode(name: "Sierra Leone", alpha2: "SL", alpha3: "SLE"),
        CountryCode(name: "Singapore", alpha2: "SG", alpha3: "SGP"),
        CountryCode(name: "Sint Maarten (Dutch part)", alpha2: "SX", alpha3: "SXM"),
        CountryCode(name: "Slovakia", alpha2: "SK", alpha3: "SVK"),
        CountryCode(name: "Slovenia", alpha2: "SI", alpha3: "SVN"),
        CountryCode(name: "Solomon Islands", alpha2: "SB", alpha3: "SLB"),
        CountryCode(name: "Somalia", alpha2: "SO", alpha3: "SOM"),
        CountryCode(name: "South Africa", alpha2: "ZA", alpha3: "ZAF"),
        CountryCode(name: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS"),
        CountryCode(name: "South Sudan", alpha2: "SS", alpha3: "SSD"),
        CountryCode(name: "Spain", alpha2: "ES", alpha3: "ESP"),
        CountryCode(name: "Sri Lanka", alpha2: "LK", alpha3: "LKA"),
        CountryCode(name: "Sudan", alpha2: "SD", alpha3: "SDN"),
        CountryCode(name: "Suriname", alpha2: "SR", alpha3: "SUR"),
        CountryCode(name: "Svalbard and Jan Mayen", alpha2: "SJ", alpha3: "SJM"),
        CountryCode(name: "Sweden", alpha2: "SE", alpha3: "SWE"),
        CountryCode(name: "Switzerland", alpha2: "CH", alpha3: "CHE"),
        CountryCode(name: "Syrian Arab Republic", alpha2: "SY", alpha3: "SYR"),
        CountryCode(name: "Taiwan, Province of China", alpha2: "TW", alpha3: "TWN"),
        CountryCode(name: "Tajikistan", alpha2: "TJ", alpha3: "TJK"),
        CountryCode(name: "Tanzania, United Republic of", alpha2: "TZ", alpha3: "TZA"),
        CountryCode(name: "Thailand", alpha2: "TH", alpha3: "THA"),
        CountryCode(name: "Timor-Leste", alpha2: "TL", alpha3: "TLS"),
        CountryCode(name: "Togo", alpha2: "TG", alpha3: "TGO"),
        CountryCode(name: "Tokelau", alpha2: "TK", alpha3: "TKL"),
        CountryCode(name: "Tonga", alpha2: "TO", alpha3: "TON"),
        CountryCode(name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO"),
        CountryCode(name: "Tunisia", alpha2: "TN", alpha3: "TUN"),
        CountryCode(name: "Türkiye", alpha2: "TR", alpha3: "TUR"),
        CountryCode(name: "Turkmenistan", alpha2: "TM", alpha3: "TKM"),
        CountryCode(name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA"),
        CountryCode(name: "Tuvalu", alpha2: "TV", alpha3: "TUV"),
        CountryCode(name: "Uganda", alpha2: "UG", alpha3: "UGA"),
        CountryCode(name: "Ukraine", alpha2: "UA", alpha3: "UKR"),
        CountryCode(name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE"),
        CountryCode(name: "United Kingdom of Great Britain and Northern Ireland", alpha2: "GB", alpha3: "GBR"),
        CountryCode(name: "United States of America", alpha2: "US", alpha3: "USA"),
        CountryCode(name: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI"),
        CountryCode(name: "Uruguay", alpha2: "UY", alpha3: "URY"),
        CountryCode(name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB"),
        CountryCode(name: "Vanuatu", alpha2: "VU", alpha3: "VUT"),
        CountryCode(name: "Venezuela, Bolivarian Republic of", alpha2: "VE", alpha3: "VEN"),
        CountryCode(name: "Viet Nam", alpha2: "VN", alpha3: "VNM"),
        CountryCode(name: "Virgin Islands (British)", alpha2: "VG", alpha3: "VGB"),
        CountryCode(name: "Virgin Islands (U.S.)", alpha2: "VI", alpha3: "VIR"),
        CountryCode(name: "Wallis and Futuna", alpha2: "WF", alpha3: "WLF"),
        CountryCode(name: "Western Sahara", alpha2: "EH", alpha3: "ESH"),
        CountryCode(name: "Yemen", alpha2: "YE", alpha3: "YEM"),
        CountryCode(name: "Zambia", alpha2: "ZM", alpha3: "ZMB"),
        CountryCode(name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE"),
    ]

    static func alpha2ToAlpha3(_ alpha2: String) -> String? {
        return _countries.first(where: { $0.alpha2 == alpha2 })?.alpha3
    }

    static func alpha3ToAlpha2(_ alpha3: String) -> String? {
        return _countries.first(where: { $0.alpha3 == alpha3 })?.alpha2
    }
}
